apiVersion: v1
kind: ConfigMap
metadata:
  name: database-backup-config
data:

  #database section
  DATABASE_BACKUP_SERVER_HOST: "db.zhangyongqiao.com"
  DATABASE_BACKUP_SERVER_USER: root
  DATABASE_BACKUP_SERVER_PASSWORD: root_password
  DATABASE_BACKUP_PATH: thingsminder

