version: "3.7"

networks:
  service-network:
    name: service-network


services:
 
  # drone使用mysql
  drone_mysql:
    image: mysql
    restart: always
    container_name: drone_mysql
    ports:
      - 33066:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - default
    volumes:
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:rw
      - /var/release/drone_mysql/data:/var/lib/mysql/:rw
      - /var/release/drone_mysql/logs:/var/log/mysql/:rw

  # drone 服务端
  drone_server:
    image: ${DRONE_DOCKER_IMAGE}
    # labels:
    #   - "traefik.http.routers.whoami.rule=Host(`drone.zhangyongqiao.com`)"
    container_name: drone_server
    ports:
      - 9999:80 # drone comtainer serves via port 80, we expose to end users via port 8381
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/release/drone_server/data:/data:rw
      - /var/release/drone_server/drone:/var/lib/drone:rw
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    restart: always
    environment:
      # db Config
      - DRONE_DATABASE_DATASOURCE=${MYSQL_DATABASE}:${MYSQL_PASSWORD}@tcp(drone_mysql:3306)/drone?parseTime=true #mysql配置，要与上边mysql容器中的配置一致
      - DRONE_DATABASE_DRIVER=mysql

      - DRONE_TLS_AUTOCERT=false

      # gitea Config
      #- DRONE_GITEA_SERVER=${GIT_SERVER} # this is internal communication with gitea server on the same network
      #- DRONE_GITEA_CLIENT_ID=${DRONE_GITEA_CLIENT_ID}
      #- DRONE_GITEA_CLIENT_SECRET=${DRONE_GITEA_CLIENT_SECRET}
      #gitee 
      
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GIT_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GIT_CLIENT_SECRET}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET} #RPC秘钥
      - DRONE_SERVER_HOST=${DRONE_HOST}
      - DRONE_SERVER_PROTO=http
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_GIT_ALWAYS_AUTH=true
      - DRONE_USER_CREATE=username:${DRONE_ADMIN_USERNAME},admin:true #管理员账号，是你想要作为管理员的Gitea用户名
      # droneclient Config

      # dronelog
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true
      - DRONE_LOGS_TEXT=true
      - DRONE_LOGS_DEBUG=true
      - DRONE_LOGS_TRACE=true
    depends_on:
      - drone_mysql
    networks:
      - default

  drone-runner:
    image: ${DRONE_RUNNER_DOCKER_IMAGE}
    # labels:
    #   - "traefik.http.routers.dronerunner.rule=Host(`drone.zhangyongqiao.com`)"
    container_name: drone_runner
    expose:
      - 3000
    environment:
      - DRONE_GIT_ALWAYS_AUTH=true
      - DRONE_RPC_PROTO=http
      # - DRONE_RPC_HOST=${DRONE_HOST}
      - DRONE_RPC_HOST=drone_server:80
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_CAPACITY=${DRONE_RUNNER_CAPACITY}
    networks:
      - default
    depends_on:
      - drone_server
      - drone_mysql
    restart: always
    volumes:
      # 标准 Linux 系统下使用
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/release/drone_runner:/data
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    #extra_hosts:
    #  - "${SERVICE_DOMAIN}:127.0.0.1"


  # docker-repo:
  #   image: ${DOCKER_REPO_DOCKER_IMAGE}
  #   container_name: docker_registry
  #   ports:
  #     - 5000:5000
  #   environment:
  #     - DRONE_RPC_PROTO=http
  #   networks:
  #     - dronenet
  #   depends_on:
  #     - drone_server
  #   restart: always
  #   volumes:
  #     # 标准 Linux 系统下使用
  #     # - /etc/localtime:/etc/localtime:ro
  #     # - /etc/timezone:/etc/timezone:ro
  #     - /data/docker/registry:/var/lib/registry
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "50m"
  #   #extra_hosts:
  #   #  - "${SERVICE_DOMAIN}:127.0.0.1"
 
 