---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-backup-script-config
data:
  backup.sh: |
    #/bin/bash

    #保存备份文件最多个数
    count=10

    #备份保存路径
    backup_path=/data-backup
    if [ -z '$DATABASE_BACKUP_PATH' ];
    then
       backup_path=/data-backup
    else
       backup_path=/data-backup/$DATABASE_BACKUP_PATH
    fi

    echo BACKUP_PATH_LOCATE $backup_path
    #备份保存路径
  


    

    #host
    host=$DATABASE_BACKUP_SERVER_HOST
    #用户名
    username=$DATABASE_BACKUP_SERVER_USER
    #密码
    password=$DATABASE_BACKUP_SERVER_PASSWORD
    
    #将要备份的数据库
    database_name=test
    
    backup_filename=$backup_path/latest.sql;
    backup_text_filename=$backup_path/latest.txt;
 
    #日期
    date_time=`date +%Y-%m-%d-%H-%M`
 
    #如果文件夹不存在则创建
    if [ ! -d $backup_path ]; 
    then 
      mkdir -p $backup_path;
      chmod 777 -R $backup_path;
    fi
    #开始备份
    if [ -z "$BACKUP_DATABASE_NAME" ];
    then
      database_name=--all-databases;
      backup_filename=all-$date_time;
    else
      database_name=$BACKUP_DATABASE_NAME;
      backup_filename=$database_name-$date_time;
    fi

    echo BACKUP_PATH_LOCATE-$backup_path
    echo BACKUP_DATABASE-$database_name

    #mysqldump -u $username -p$password --master-data=2 --default-character-set=utf8 --single-transaction --all-databases  > $backup_path/$database_name-$date_time.sql
    cd $backup_path
    mysqldump -h$host -u $username -p$password --single-transaction $database_name > $backup_filename.sql
    #开始压缩
    tar -zcvf $backup_filename.tar.gz $backup_filename.sql
    #删除源文件
    rm -rf $backup_filename.sql
    #更新备份日志
    echo "create $backup_filename.sql.tar.gz" >> $backup_path/dump.log
 
    #找出需要删除的备份
    delfile=`ls -l -crt $backup_path/*.tar.gz | awk '{print $9 }' | head -1`
                                                                                    
    #判断现在的备份数量是否大于阈值
    number=`ls -l -crt $backup_path/*.tar.gz | awk '{print $9 }' | wc -l`
 
    if [ $number -gt $count ]
    then
      #删除最早生成的备份，只保留count数量的备份
      rm $delfile
      #更新删除文件日志
      echo "delete $delfile" >> $backup_path/dump.log
    fi



