---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my.cnf
data:
  my.cnf: |
    [mysqld]
    #skip-name-resolve
    port = 3306
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    skip-character-set-client-handshake=1
    default-storage-engine=INNODB
    max_allowed_packet = 500M
    explicit_defaults_for_timestamp=1
    long_query_time = 10
    max_connections = 1500
    sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    secure_file_priv=/var/lib/mysql

    [client]
    default-character-set=utf8mb4
    [mysql]
    default-character-set=utf8mb4


